### ISSUE TITLE
Implement DBW node

### ISSUE THREAD

**Issue by hrektts** [nouriss/CarND-Capstone-CognitiveBot#4]
>DBW Node: Once your waypoint updater is publishing /final_waypoints, the waypoint_follower node will start publishing messages to the/twist_cmd topic. At this point, you have everything needed to build the dbw_node. After completing this step, the car should drive in the simulator, ignoring the traffic lights.

- [x] Publish topic
- [x] Subscribe topic
- [x] Implement a controller that can ignore the traffic lights

**Comment by nouriss** [comment]
Hi Katsotushi,

Thanks for the bugfixes ;), 

What's your your actual development status? I would be testing the  waypoint_updater  with the dbw_test.py.

I think we should discuss the dbw_node.py, Do you have ideas about implementing the controllers.
we can use the gmail hangout for chatting and exchanging ideas.

I hope that the other guys would join us soon!!

**Comment by hrektts** [comment]
Hi Nour,

Thank you for your message!

I tested the throttle publisher with a constant value (=1.0) and notice
that the simulator did not work well...
At first, I have to fix my development environment...

My plan is that first I will implement naive controller using PID and
YawController provided by Udacity
, and second, fix it after the other work done.

Katsutoshi

**Comment by nouriss** [comment]
Hi Katsotushi,

I have just finished the second task the DBW_node implementation and its related controllers, and I think I have some pretty good results ;)
Please check my last commit and let's discuss how we could improve it using your controller. 

By the way you can install "zube" from the packages here on github. it's great tool for project monitoring :+1:  

Nour

**Comment by hrektts** [comment]
LTMG! ([05de1183f357a14442af8b4a3faaf8f2b3ec8a88](https://github.com/nouriss/CarND-Capstone-CognitiveBot/tree/05de1183f357a14442af8b4a3faaf8f2b3ec8a88))
